### ISSUE TITLE
Passing Config to CLI

### ISSUE THREAD

**Issue by grantkee** [Telcoin-Association/telcoin-network#38]
# Problem
The config isn't supported in subcommands of `genesis`.

`telcoin-network genesis init --config ./path.yaml` is invalid because the config arg is only on genesis.

Passing `telcoin-network genesis --config ./path.yaml init` also doesn't work because init doesn't have a config argument.

## Desired UX
Specify only a few configuration parameters and pass the config path argument. The config should load, keep the values that are specified, and use defaults for all others.

Example local test_config.yaml with faster block production times:
```yaml
parameters:
  max_header_delay: 5s
  min_header_delay: 100ms
  max_batch_delay: 1s
```

These values should override the defaults when the config loads when the following command is executed:
`telcoin-network genesis init --config test_config.yaml`
